//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taman.io.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public int id { get; set; }
        public int balance { get; set; }
        public int user_id { get; set; }
        public byte[] created_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
